version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
    - "80:80"
#   - "443:443"
    volumes:
    - ../frontend/seqarc/build/:/usr/share/nginx/html/:ro
    - ./nginx.conf:/etc/nginx/nginx.conf
#    - ./ssl:/etc/nginx/ssl
    - "/etc/localtime:/etc/localtime:ro"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'seqarc'
      MYSQL_USER: 'seqarc'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
#   ports:
#     - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
  samplemanager:
    build: .
#   ports:
#   - "8080:8080"
#   command: ["./wait-for-postgres.sh", "postgres", "java", "-jar", "*.jar"]
    restart: on-failure
    volumes:
    - "./log:/log"
    - "../frontend/seqarc/build/samples:/samples"
    - "/etc/localtime:/etc/localtime:ro"


